import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Download, Save } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { getPublicCartaUrl, getQrImageUrl } from '../../components/admin/QrCartaModal';
import PortadasManager from '../../components/admin/PortadasManager';

type ConfiguracionRestaurante = { id: string; nombre: string; logo_url: string | null; portada_url: string | null; color_principal: string | null; descripcion: string | null; direccion: string | null; telefono: string | null; redes_sociales: Record<string, string> | null; horario: string | null; qr_url: string | null; dominio: string | null; url_reservas_mesa: string | null; activo: boolean | null };
const EMPTY: ConfiguracionRestaurante = { id: '', nombre: '', logo_url: null, portada_url: null, color_principal: '#c8a96e', descripcion: null, direccion: null, telefono: null, redes_sociales: {}, horario: null, qr_url: null, dominio: null, url_reservas_mesa: null, activo: true };
function errorMessage(error: unknown): string { if (error instanceof Error) return error.message; if (error && typeof error === 'object') { const value = error as { message?: unknown; details?: unknown; hint?: unknown; code?: unknown }; if (typeof value.message === 'string' && value.message.trim()) return value.message; if (typeof value.details === 'string' && value.details.trim()) return value.details; if (typeof value.hint === 'string' && value.hint.trim()) return value.hint; if (typeof value.code === 'string' && value.code.trim()) return `Error ${value.code}`; } return 'Se produjo un error inesperado.'; }
function normalizeConfig(config: ConfiguracionRestaurante): ConfiguracionRestaurante { return { ...config, nombre: config.nombre.trim(), logo_url: config.logo_url?.trim() || null, portada_url: config.portada_url?.trim() || null, color_principal: config.color_principal?.trim() || null, descripcion: config.descripcion?.trim() || null, direccion: config.direccion?.trim() || null, telefono: config.telefono?.trim() || null, horario: config.horario?.trim() || null, qr_url: config.qr_url?.trim() || null, dominio: config.dominio?.trim() || null, url_reservas_mesa: config.url_reservas_mesa?.trim() || null, redes_sociales: { instagram: config.redes_sociales?.instagram?.trim() || '', facebook: config.redes_sociales?.facebook?.trim() || '', web: config.redes_sociales?.web?.trim() || '' } }; }
function snapshot(config: ConfiguracionRestaurante): string { return JSON.stringify(normalizeConfig(config)); }
function Field({ label, value, onChange, placeholder, type = 'text', required = false }: { label: string; value: string; onChange: (v: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <label className="block min-w-0"><span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-[var(--app-muted)]">{label}{required && <span className="ml-1 text-red-500">*</span>}</span><input type={type} required={required} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-9 w-full min-w-0 rounded-md border border-[var(--app-border)] bg-[var(--app-surface-soft)] px-2.5 text-xs text-[var(--app-text)] outline-none placeholder:text-[var(--app-muted)] focus:border-orange-400/60" /></label>; }

export default function AdminConfiguracion() {
  const [config, setConfig] = useState(EMPTY); const [initialSnapshot, setInitialSnapshot] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [downloadingQr, setDownloadingQr] = useState(false); const [confirmSave, setConfirmSave] = useState(false); const [confirmDownload, setConfirmDownload] = useState(false); const [error, setError] = useState<string | null>(null);
  const publicUrl = useMemo(() => getPublicCartaUrl(config.dominio), [config.dominio]); const qrImageUrl = getQrImageUrl(publicUrl, config.qr_url); const hasChanges = Boolean(config.id) && snapshot(config) !== initialSnapshot; const qrLinkValid = Boolean(config.dominio?.trim());
  const load = async () => { setLoading(true); setError(null); try { const { data, error: queryError } = await supabase.from('configuracion_restaurante').select('*').eq('activo', true).limit(1).maybeSingle(); if (queryError) throw queryError; if (data) { const loaded = { ...EMPTY, ...data, redes_sociales: data.redes_sociales ?? {} }; setConfig(loaded); setInitialSnapshot(snapshot(loaded)); } } catch (e) { setError(errorMessage(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const set = (key: keyof ConfiguracionRestaurante, value: string) => setConfig((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!config.id || !hasChanges || saving) return; if (!qrLinkValid) { setError('El enlace QR para abrir la carta es obligatorio. Sin ese enlace no se puede generar un QR válido.'); return; } setSaving(true); setSaved(false); setError(null); try { const next = normalizeConfig(config); const { error: updateError } = await supabase.from('configuracion_restaurante').update({ nombre: next.nombre, logo_url: next.logo_url, portada_url: next.portada_url, color_principal: next.color_principal, descripcion: next.descripcion, direccion: next.direccion, telefono: next.telefono, horario: next.horario, qr_url: next.qr_url, dominio: next.dominio, url_reservas_mesa: next.url_reservas_mesa, redes_sociales: next.redes_sociales, updated_at: new Date().toISOString() }).eq('id', next.id); if (updateError) throw updateError; setConfig(next); setInitialSnapshot(snapshot(next)); setSaved(true); setConfirmSave(false); window.setTimeout(() => setSaved(false), 2200); } catch (e) { setError(errorMessage(e)); } finally { setSaving(false); } };
  const downloadQr = async () => { setConfirmDownload(false); setDownloadingQr(true); setError(null); try { if (!qrLinkValid) throw new Error('Configura primero el enlace QR obligatorio.'); const response = await fetch(qrImageUrl); if (!response.ok) throw new Error('No se pudo descargar el código QR.'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'carta-qr.png'; document.body.appendChild(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); } catch (e) { setError(errorMessage(e)); } finally { setDownloadingQr(false); } };
  if (loading) return <div className="flex min-h-[60vh] w-full items-center justify-center" style={{ background: 'var(--app-bg)' }}><div className="h-7 w-7 animate-spin rounded-full border-b-2 border-orange-400" /></div>;
  return <div className="mx-0 min-h-[calc(100dvh-1rem)] w-full min-w-0 max-w-none overflow-x-hidden pb-5 text-[var(--app-text)]">
    <header className="sticky top-0 z-30 flex h-12 min-w-0 items-center gap-2 border-b bg-[var(--app-bg)]/95 backdrop-blur" style={{ borderColor: 'var(--app-border)' }}><Link to="/admin" className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-lg text-[var(--app-muted)] hover:bg-black/5 dark:hover:bg-white/5" aria-label="Volver al inicio"><ArrowLeft size={19} /></Link><div className="min-w-0"><h1 className="text-lg font-extrabold">Configuración</h1><p className="text-[9px] font-semibold uppercase tracking-wide text-[var(--app-muted)]">Datos de la carta</p></div><button type="button" onClick={() => setConfirmSave(true)} disabled={saving || !hasChanges || !qrLinkValid} className="ml-auto inline-flex h-8 flex-shrink-0 items-center gap-1 rounded-md bg-orange-400 px-2.5 text-xs font-extrabold text-[#111] disabled:opacity-45"><Save size={14} />{saving ? 'Guardando…' : 'Guardar'}</button></header>
    {error && <div className="mt-2 w-full min-w-0 rounded-xl border border-red-400/20 bg-[var(--app-surface)] p-3 text-xs text-red-400">{error}<button type="button" onClick={() => void load()} className="ml-2 font-bold text-orange-400">Reintentar</button></div>}
    <section className="mt-2 w-full min-w-0 rounded-xl border bg-[var(--app-surface)] p-2.5" style={{ borderColor: 'var(--app-border)' }}><div className="mb-2 flex min-w-0 items-center justify-between gap-2"><div className="min-w-0"><h2 className="text-sm font-extrabold">Restaurante</h2><p className="text-[9px] text-[var(--app-muted)]">Información que verá el cliente en la carta.</p></div><span className="flex-shrink-0 rounded-full bg-green-400/10 px-2 py-0.5 text-[9px] font-bold text-green-500">Activo</span></div><div className="grid min-w-0 gap-2 sm:grid-cols-2"><Field label="Nombre" value={config.nombre} onChange={(v) => set('nombre', v)} /><Field label="Teléfono" value={config.telefono ?? ''} onChange={(v) => set('telefono', v)} type="tel" /><div className="min-w-0 sm:col-span-2"><Field label="Dirección" value={config.direccion ?? ''} onChange={(v) => set('direccion', v)} /></div><div className="min-w-0 sm:col-span-2"><label className="block"><span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-[var(--app-muted)]">Descripción</span><textarea value={config.descripcion ?? ''} onChange={(e) => set('descripcion', e.target.value)} rows={2} className="w-full min-w-0 resize-none rounded-md border bg-[var(--app-surface-soft)] px-2.5 py-1.5 text-xs text-[var(--app-text)] outline-none focus:border-orange-400/60" style={{ borderColor: 'var(--app-border)' }} /></label></div><div className="min-w-0 sm:col-span-2"><label className="block"><span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-[var(--app-muted)]">Horario</span><textarea value={config.horario ?? ''} onChange={(e) => set('horario', e.target.value)} rows={2} className="w-full min-w-0 resize-none rounded-md border bg-[var(--app-surface-soft)] px-2.5 py-1.5 text-xs text-[var(--app-text)] outline-none focus:border-orange-400/60" style={{ borderColor: 'var(--app-border)' }} /></label></div></div></section>
    {config.id && <PortadasManager configuracionId={config.id} onPortadaActualChange={(url) => setConfig((current) => ({ ...current, portada_url: url }))} />}
    <section className="mt-2 w-full min-w-0 rounded-xl border bg-[var(--app-surface)] p-2.5" style={{ borderColor: 'var(--app-border)' }}><h2 className="text-sm font-extrabold">Código QR de la carta</h2><p className="mb-2 text-[9px] text-[var(--app-muted)]">El QR se genera con el enlace que introduzcas. Ese enlace es obligatorio.</p><div className="grid min-w-0 gap-3 sm:grid-cols-[150px_minmax(0,1fr)] sm:items-center"><div className="flex flex-col items-center justify-center rounded-xl bg-white p-2">{qrImageUrl ? <img src={qrImageUrl} alt="Código QR de la carta" className="h-32 w-32 object-contain" /> : <div className="flex h-32 w-32 items-center justify-center px-3 text-center text-[10px] font-bold text-slate-500">Introduce el enlace QR obligatorio</div>}<button type="button" onClick={() => setConfirmDownload(true)} disabled={downloadingQr || !qrLinkValid} className="mt-1 inline-flex h-8 items-center gap-1 rounded-md px-2 text-[10px] font-extrabold text-orange-500 disabled:opacity-50"><Download size={14} />{downloadingQr ? 'Descargando…' : 'Descargar QR'}</button></div><div className="min-w-0 space-y-2"><Field label="Enlace QR para abrir la carta" value={config.dominio ?? ''} onChange={(v) => set('dominio', v)} placeholder="https://tudominio.com/carta" type="url" required /><p className={`text-[9px] font-semibold ${qrLinkValid ? 'text-[var(--app-muted)]' : 'text-red-500'}`}>Obligatorio. Este es el enlace que codifica el QR.</p><Field label="Imagen QR personalizada" value={config.qr_url ?? ''} onChange={(v) => set('qr_url', v)} placeholder="https://…" /></div></div></section>
    <section className="mt-2 w-full min-w-0 rounded-xl border bg-[var(--app-surface)] p-2.5" style={{ borderColor: 'var(--app-border)' }}><h2 className="text-sm font-extrabold">Reserva de mesa</h2><p className="mb-2 text-[9px] text-[var(--app-muted)]">Aplicación externa que se abrirá al pulsar "Reservar mesa".</p><Field label="Programa de reservas de mesa" value={config.url_reservas_mesa ?? ''} onChange={(v) => set('url_reservas_mesa', v)} placeholder="https://…" type="url" /></section>
    <section className="mt-2 w-full min-w-0 rounded-xl border bg-[var(--app-surface)] p-2.5" style={{ borderColor: 'var(--app-border)' }}><h2 className="text-sm font-extrabold">Identidad visual</h2><p className="mb-2 text-[9px] text-[var(--app-muted)]">Logo y color principal de la carta.</p><div className="grid min-w-0 gap-2 sm:grid-cols-2"><Field label="URL del logotipo" value={config.logo_url ?? ''} onChange={(v) => set('logo_url', v)} placeholder="https://…" /><label className="block min-w-0"><span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-[var(--app-muted)]">Color principal</span><div className="flex h-9 min-w-0 gap-2"><input type="color" value={config.color_principal || '#c8a96e'} onChange={(e) => set('color_principal', e.target.value)} className="h-9 w-11 flex-shrink-0 rounded-md border bg-[var(--app-surface-soft)] p-1" style={{ borderColor: 'var(--app-border)' }} /><input value={config.color_principal ?? ''} onChange={(e) => set('color_principal', e.target.value)} className="min-w-0 flex-1 rounded-md border bg-[var(--app-surface-soft)] px-2.5 text-xs text-[var(--app-text)] outline-none focus:border-orange-400/60" style={{ borderColor: 'var(--app-border)' }} /></div></label></div></section>
    <section className="mt-2 w-full min-w-0 rounded-xl border bg-[var(--app-surface)] p-2.5" style={{ borderColor: 'var(--app-border)' }}><h2 className="text-sm font-extrabold">Redes sociales</h2><p className="mb-2 text-[9px] text-[var(--app-muted)]">Enlaces opcionales que puede mostrar la carta.</p><div className="grid min-w-0 gap-2 sm:grid-cols-2">{(['instagram', 'facebook', 'web'] as const).map((key) => <Field key={key} label={key} value={config.redes_sociales?.[key] ?? ''} onChange={(value) => setConfig((current) => ({ ...current, redes_sociales: { ...(current.redes_sociales ?? {}), [key]: value } }))} placeholder="https://…" />)}</div></section>
    <button type="button" onClick={() => setConfirmSave(true)} disabled={saving || !hasChanges || !qrLinkValid} className="mt-2 flex h-10 w-full min-w-0 items-center justify-center gap-2 rounded-md bg-orange-400 text-xs font-extrabold text-[#111] disabled:opacity-45"><Save size={15} />{saving ? 'Guardando…' : 'Guardar configuración'}</button>{saved && <div className="mt-2 flex w-full min-w-0 items-center justify-center gap-1.5 rounded-md border border-green-400/30 bg-green-400/10 px-3 py-2 text-xs font-bold text-green-500">Cambios guardados correctamente.</div>}
    {confirmSave && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-sm rounded-2xl border bg-[var(--app-surface)] p-5 shadow-xl" style={{ borderColor: 'var(--app-border)' }}><h3 className="text-base font-extrabold">Guardar cambios</h3><p className="mt-2 text-sm text-[var(--app-muted)]">¿Quieres guardar los cambios realizados en la configuración?</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setConfirmSave(false)} className="rounded-lg border px-4 py-2 text-sm font-bold" style={{ borderColor: 'var(--app-border)' }}>Cancelar</button><button type="button" onClick={() => void save()} disabled={saving} className="rounded-lg bg-orange-400 px-4 py-2 text-sm font-extrabold text-[#111] disabled:opacity-50">{saving ? 'Guardando…' : 'Guardar'}</button></div></div></div>}
    {confirmDownload && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-sm rounded-2xl border bg-[var(--app-surface)] p-5 shadow-xl" style={{ borderColor: 'var(--app-border)' }}><h3 className="text-base font-extrabold">Descargar QR</h3><p className="mt-2 text-sm text-[var(--app-muted)]">Se va a descargar el código QR de la carta. ¿Quieres continuar?</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setConfirmDownload(false)} className="rounded-lg border px-4 py-2 text-sm font-bold" style={{ borderColor: 'var(--app-border)' }}>Cancelar</button><button type="button" onClick={() => void downloadQr()} disabled={downloadingQr || !qrLinkValid} className="rounded-lg bg-orange-400 px-4 py-2 text-sm font-extrabold text-[#111] disabled:opacity-50">{downloadingQr ? 'Descargando…' : 'Descargar'}</button></div></div></div>}
  </div>;
}
